name: Deploy Admin Dashboard to Firebase Hosting on merge
'on':
  push:
    branches:
      - main
    paths:
      - 'admin-dashboard/**'
      - '.github/workflows/deploy-admin.yml'
      
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./admin-dashboard
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build
        run: npm run build
        
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_LINE_BOT_407102 }}'
          channelId: live
          projectId: line-bot-407102
          target: shop-pwa-demo-admin
          entryPoint: ./admin-dashboard